#Enable growth particles
showParticles = true
#Use whitelist only. (will override blacklist and onlySaplingsAndCrops)
useWhitelistOnly = true
#Whitelist of blocks that will grow.
whiteList = ["minecraft:bamboo", "minecraft:bamboo_sapling"]
#Blacklist of blocks that will not grow.
blackList = []
#Only grow sapling tags and crop tags. (blacklist can exclude these)
onlySaplingsAndCrops = false
#The distance from the player to check for growth in blocks. (N S E W)
# Default: 5
# Range: 1 ~ 20
playerDistance = 5
#The chance of growth applied by sprinting. (1 = 100%)
# Default: 0.075
# Range: 0.0 ~ 1.0
sprintGrowthChance = 0.0
#The chance of growth applied by crouching. (1 = 100%)
# Default: 0.15
# Range: 0.0 ~ 1.0
crouchGrowthChance = 0.25
